import json


def flag(code):
    return "".join(chr(0x1F1E6 + ord(char) - ord("A")) for char in code)


rows = [
    ("AF", "Afghanistan", "阿富汗", "Kabul", "Asia", []),
    ("AL", "Albania", "阿尔巴尼亚", "Tirana", "Europe", []),
    ("DZ", "Algeria", "阿尔及利亚", "Algiers", "Africa", []),
    ("AD", "Andorra", "安道尔", "Andorra la Vella", "Europe", []),
    ("AO", "Angola", "安哥拉", "Luanda", "Africa", []),
    ("AG", "Antigua and Barbuda", "安提瓜和巴布达", "Saint John's", "North America", ["Antigua"]),
    ("AR", "Argentina", "阿根廷", "Buenos Aires", "South America", []),
    ("AM", "Armenia", "亚美尼亚", "Yerevan", "Asia", []),
    ("AU", "Australia", "澳大利亚", "Canberra", "Oceania", []),
    ("AT", "Austria", "奥地利", "Vienna", "Europe", []),
    ("AZ", "Azerbaijan", "阿塞拜疆", "Baku", "Asia", []),
    ("BS", "Bahamas", "巴哈马", "Nassau", "North America", ["The Bahamas"]),
    ("BH", "Bahrain", "巴林", "Manama", "Asia", []),
    ("BD", "Bangladesh", "孟加拉国", "Dhaka", "Asia", []),
    ("BB", "Barbados", "巴巴多斯", "Bridgetown", "North America", []),
    ("BY", "Belarus", "白俄罗斯", "Minsk", "Europe", []),
    ("BE", "Belgium", "比利时", "Brussels", "Europe", []),
    ("BZ", "Belize", "伯利兹", "Belmopan", "North America", []),
    ("BJ", "Benin", "贝宁", "Porto-Novo", "Africa", []),
    ("BT", "Bhutan", "不丹", "Thimphu", "Asia", []),
    ("BO", "Bolivia", "玻利维亚", "Sucre", "South America", ["Bolivia (Plurinational State of)"]),
    ("BA", "Bosnia and Herzegovina", "波斯尼亚和黑塞哥维那", "Sarajevo", "Europe", ["Bosnia"]),
    ("BW", "Botswana", "博茨瓦纳", "Gaborone", "Africa", []),
    ("BR", "Brazil", "巴西", "Brasilia", "South America", []),
    ("BN", "Brunei", "文莱", "Bandar Seri Begawan", "Asia", ["Brunei Darussalam"]),
    ("BG", "Bulgaria", "保加利亚", "Sofia", "Europe", []),
    ("BF", "Burkina Faso", "布基纳法索", "Ouagadougou", "Africa", []),
    ("BI", "Burundi", "布隆迪", "Gitega", "Africa", []),
    ("CV", "Cabo Verde", "佛得角", "Praia", "Africa", ["Cape Verde"]),
    ("KH", "Cambodia", "柬埔寨", "Phnom Penh", "Asia", []),
    ("CM", "Cameroon", "喀麦隆", "Yaounde", "Africa", []),
    ("CA", "Canada", "加拿大", "Ottawa", "North America", []),
    ("CF", "Central African Republic", "中非共和国", "Bangui", "Africa", ["CAR"]),
    ("TD", "Chad", "乍得", "N'Djamena", "Africa", []),
    ("CL", "Chile", "智利", "Santiago", "South America", []),
    ("CN", "China", "中国", "Beijing", "Asia", ["People's Republic of China", "PRC"]),
    ("CO", "Colombia", "哥伦比亚", "Bogota", "South America", []),
    ("KM", "Comoros", "科摩罗", "Moroni", "Africa", []),
    ("CG", "Congo", "刚果共和国", "Brazzaville", "Africa", ["Republic of the Congo", "Congo-Brazzaville"]),
    ("CR", "Costa Rica", "哥斯达黎加", "San Jose", "North America", []),
    ("CI", "Cote d'Ivoire", "科特迪瓦", "Yamoussoukro", "Africa", ["Ivory Coast", "Côte d'Ivoire"]),
    ("HR", "Croatia", "克罗地亚", "Zagreb", "Europe", []),
    ("CU", "Cuba", "古巴", "Havana", "North America", []),
    ("CY", "Cyprus", "塞浦路斯", "Nicosia", "Asia", []),
    ("CZ", "Czechia", "捷克", "Prague", "Europe", ["Czech Republic"]),
    ("KP", "North Korea", "朝鲜", "Pyongyang", "Asia", ["DPRK", "Democratic People's Republic of Korea"]),
    ("CD", "Democratic Republic of the Congo", "刚果民主共和国", "Kinshasa", "Africa", ["DRC", "Congo-Kinshasa"]),
    ("DK", "Denmark", "丹麦", "Copenhagen", "Europe", []),
    ("DJ", "Djibouti", "吉布提", "Djibouti", "Africa", []),
    ("DM", "Dominica", "多米尼克", "Roseau", "North America", []),
    ("DO", "Dominican Republic", "多米尼加共和国", "Santo Domingo", "North America", []),
    ("EC", "Ecuador", "厄瓜多尔", "Quito", "South America", []),
    ("EG", "Egypt", "埃及", "Cairo", "Africa", []),
    ("SV", "El Salvador", "萨尔瓦多", "San Salvador", "North America", []),
    ("GQ", "Equatorial Guinea", "赤道几内亚", "Malabo", "Africa", []),
    ("ER", "Eritrea", "厄立特里亚", "Asmara", "Africa", []),
    ("EE", "Estonia", "爱沙尼亚", "Tallinn", "Europe", []),
    ("SZ", "Eswatini", "斯威士兰", "Mbabane", "Africa", ["Swaziland"]),
    ("ET", "Ethiopia", "埃塞俄比亚", "Addis Ababa", "Africa", []),
    ("FJ", "Fiji", "斐济", "Suva", "Oceania", []),
    ("FI", "Finland", "芬兰", "Helsinki", "Europe", []),
    ("FR", "France", "法国", "Paris", "Europe", []),
    ("GA", "Gabon", "加蓬", "Libreville", "Africa", []),
    ("GM", "Gambia", "冈比亚", "Banjul", "Africa", ["The Gambia"]),
    ("GE", "Georgia", "格鲁吉亚", "Tbilisi", "Asia", []),
    ("DE", "Germany", "德国", "Berlin", "Europe", []),
    ("GH", "Ghana", "加纳", "Accra", "Africa", []),
    ("GR", "Greece", "希腊", "Athens", "Europe", []),
    ("GD", "Grenada", "格林纳达", "Saint George's", "North America", []),
    ("GT", "Guatemala", "危地马拉", "Guatemala City", "North America", []),
    ("GN", "Guinea", "几内亚", "Conakry", "Africa", []),
    ("GW", "Guinea-Bissau", "几内亚比绍", "Bissau", "Africa", []),
    ("GY", "Guyana", "圭亚那", "Georgetown", "South America", []),
    ("HT", "Haiti", "海地", "Port-au-Prince", "North America", []),
    ("HN", "Honduras", "洪都拉斯", "Tegucigalpa", "North America", []),
    ("HU", "Hungary", "匈牙利", "Budapest", "Europe", []),
    ("IS", "Iceland", "冰岛", "Reykjavik", "Europe", []),
    ("IN", "India", "印度", "New Delhi", "Asia", []),
    ("ID", "Indonesia", "印度尼西亚", "Jakarta", "Asia", []),
    ("IR", "Iran", "伊朗", "Tehran", "Asia", ["Islamic Republic of Iran"]),
    ("IQ", "Iraq", "伊拉克", "Baghdad", "Asia", []),
    ("IE", "Ireland", "爱尔兰", "Dublin", "Europe", []),
    ("IL", "Israel", "以色列", "Jerusalem", "Asia", []),
    ("IT", "Italy", "意大利", "Rome", "Europe", []),
    ("JM", "Jamaica", "牙买加", "Kingston", "North America", []),
    ("JP", "Japan", "日本", "Tokyo", "Asia", []),
    ("JO", "Jordan", "约旦", "Amman", "Asia", []),
    ("KZ", "Kazakhstan", "哈萨克斯坦", "Astana", "Asia", []),
    ("KE", "Kenya", "肯尼亚", "Nairobi", "Africa", []),
    ("KI", "Kiribati", "基里巴斯", "South Tarawa", "Oceania", []),
    ("KW", "Kuwait", "科威特", "Kuwait City", "Asia", []),
    ("KG", "Kyrgyzstan", "吉尔吉斯斯坦", "Bishkek", "Asia", []),
    ("LA", "Laos", "老挝", "Vientiane", "Asia", ["Lao People's Democratic Republic", "Lao PDR"]),
    ("LV", "Latvia", "拉脱维亚", "Riga", "Europe", []),
    ("LB", "Lebanon", "黎巴嫩", "Beirut", "Asia", []),
    ("LS", "Lesotho", "莱索托", "Maseru", "Africa", []),
    ("LR", "Liberia", "利比里亚", "Monrovia", "Africa", []),
    ("LY", "Libya", "利比亚", "Tripoli", "Africa", []),
    ("LI", "Liechtenstein", "列支敦士登", "Vaduz", "Europe", []),
    ("LT", "Lithuania", "立陶宛", "Vilnius", "Europe", []),
    ("LU", "Luxembourg", "卢森堡", "Luxembourg", "Europe", []),
    ("MG", "Madagascar", "马达加斯加", "Antananarivo", "Africa", []),
    ("MW", "Malawi", "马拉维", "Lilongwe", "Africa", []),
    ("MY", "Malaysia", "马来西亚", "Kuala Lumpur", "Asia", []),
    ("MV", "Maldives", "马尔代夫", "Male", "Asia", []),
    ("ML", "Mali", "马里", "Bamako", "Africa", []),
    ("MT", "Malta", "马耳他", "Valletta", "Europe", []),
    ("MH", "Marshall Islands", "马绍尔群岛", "Majuro", "Oceania", []),
    ("MR", "Mauritania", "毛里塔尼亚", "Nouakchott", "Africa", []),
    ("MU", "Mauritius", "毛里求斯", "Port Louis", "Africa", []),
    ("MX", "Mexico", "墨西哥", "Mexico City", "North America", []),
    ("FM", "Micronesia", "密克罗尼西亚", "Palikir", "Oceania", ["Federated States of Micronesia"]),
    ("MC", "Monaco", "摩纳哥", "Monaco", "Europe", []),
    ("MN", "Mongolia", "蒙古", "Ulaanbaatar", "Asia", []),
    ("ME", "Montenegro", "黑山", "Podgorica", "Europe", []),
    ("MA", "Morocco", "摩洛哥", "Rabat", "Africa", []),
    ("MZ", "Mozambique", "莫桑比克", "Maputo", "Africa", []),
    ("MM", "Myanmar", "缅甸", "Naypyidaw", "Asia", ["Burma"]),
    ("NA", "Namibia", "纳米比亚", "Windhoek", "Africa", []),
    ("NR", "Nauru", "瑙鲁", "Yaren", "Oceania", []),
    ("NP", "Nepal", "尼泊尔", "Kathmandu", "Asia", []),
    ("NL", "Netherlands", "荷兰", "Amsterdam", "Europe", ["Holland"]),
    ("NZ", "New Zealand", "新西兰", "Wellington", "Oceania", []),
    ("NI", "Nicaragua", "尼加拉瓜", "Managua", "North America", []),
    ("NE", "Niger", "尼日尔", "Niamey", "Africa", []),
    ("NG", "Nigeria", "尼日利亚", "Abuja", "Africa", []),
    ("MK", "North Macedonia", "北马其顿", "Skopje", "Europe", ["Macedonia"]),
    ("NO", "Norway", "挪威", "Oslo", "Europe", []),
    ("OM", "Oman", "阿曼", "Muscat", "Asia", []),
    ("PK", "Pakistan", "巴基斯坦", "Islamabad", "Asia", []),
    ("PW", "Palau", "帕劳", "Ngerulmud", "Oceania", []),
    ("PA", "Panama", "巴拿马", "Panama City", "North America", []),
    ("PG", "Papua New Guinea", "巴布亚新几内亚", "Port Moresby", "Oceania", ["PNG"]),
    ("PY", "Paraguay", "巴拉圭", "Asuncion", "South America", []),
    ("PE", "Peru", "秘鲁", "Lima", "South America", []),
    ("PH", "Philippines", "菲律宾", "Manila", "Asia", ["The Philippines"]),
    ("PL", "Poland", "波兰", "Warsaw", "Europe", []),
    ("PT", "Portugal", "葡萄牙", "Lisbon", "Europe", []),
    ("QA", "Qatar", "卡塔尔", "Doha", "Asia", []),
    ("KR", "South Korea", "韩国", "Seoul", "Asia", ["Republic of Korea", "Korea"]),
    ("MD", "Moldova", "摩尔多瓦", "Chisinau", "Europe", ["Republic of Moldova"]),
    ("RO", "Romania", "罗马尼亚", "Bucharest", "Europe", []),
    ("RU", "Russia", "俄罗斯", "Moscow", "Europe", ["Russian Federation"]),
    ("RW", "Rwanda", "卢旺达", "Kigali", "Africa", []),
    ("KN", "Saint Kitts and Nevis", "圣基茨和尼维斯", "Basseterre", "North America", ["St. Kitts and Nevis"]),
    ("LC", "Saint Lucia", "圣卢西亚", "Castries", "North America", ["St. Lucia"]),
    ("VC", "Saint Vincent and the Grenadines", "圣文森特和格林纳丁斯", "Kingstown", "North America", ["St. Vincent and the Grenadines"]),
    ("WS", "Samoa", "萨摩亚", "Apia", "Oceania", []),
    ("SM", "San Marino", "圣马力诺", "San Marino", "Europe", []),
    ("ST", "Sao Tome and Principe", "圣多美和普林西比", "Sao Tome", "Africa", ["São Tomé and Príncipe"]),
    ("SA", "Saudi Arabia", "沙特阿拉伯", "Riyadh", "Asia", []),
    ("SN", "Senegal", "塞内加尔", "Dakar", "Africa", []),
    ("RS", "Serbia", "塞尔维亚", "Belgrade", "Europe", []),
    ("SC", "Seychelles", "塞舌尔", "Victoria", "Africa", []),
    ("SL", "Sierra Leone", "塞拉利昂", "Freetown", "Africa", []),
    ("SG", "Singapore", "新加坡", "Singapore", "Asia", []),
    ("SK", "Slovakia", "斯洛伐克", "Bratislava", "Europe", []),
    ("SI", "Slovenia", "斯洛文尼亚", "Ljubljana", "Europe", []),
    ("SB", "Solomon Islands", "所罗门群岛", "Honiara", "Oceania", []),
    ("SO", "Somalia", "索马里", "Mogadishu", "Africa", []),
    ("ZA", "South Africa", "南非", "Pretoria", "Africa", []),
    ("SS", "South Sudan", "南苏丹", "Juba", "Africa", []),
    ("ES", "Spain", "西班牙", "Madrid", "Europe", []),
    ("LK", "Sri Lanka", "斯里兰卡", "Sri Jayawardenepura Kotte", "Asia", []),
    ("SD", "Sudan", "苏丹", "Khartoum", "Africa", []),
    ("SR", "Suriname", "苏里南", "Paramaribo", "South America", []),
    ("SE", "Sweden", "瑞典", "Stockholm", "Europe", []),
    ("CH", "Switzerland", "瑞士", "Bern", "Europe", []),
    ("SY", "Syria", "叙利亚", "Damascus", "Asia", ["Syrian Arab Republic"]),
    ("TJ", "Tajikistan", "塔吉克斯坦", "Dushanbe", "Asia", []),
    ("TH", "Thailand", "泰国", "Bangkok", "Asia", []),
    ("TL", "Timor-Leste", "东帝汶", "Dili", "Asia", ["East Timor"]),
    ("TG", "Togo", "多哥", "Lome", "Africa", []),
    ("TO", "Tonga", "汤加", "Nuku'alofa", "Oceania", []),
    ("TT", "Trinidad and Tobago", "特立尼达和多巴哥", "Port of Spain", "North America", []),
    ("TN", "Tunisia", "突尼斯", "Tunis", "Africa", []),
    ("TR", "Turkey", "土耳其", "Ankara", "Asia", ["Türkiye", "Turkiye"]),
    ("TM", "Turkmenistan", "土库曼斯坦", "Ashgabat", "Asia", []),
    ("TV", "Tuvalu", "图瓦卢", "Funafuti", "Oceania", []),
    ("UG", "Uganda", "乌干达", "Kampala", "Africa", []),
    ("UA", "Ukraine", "乌克兰", "Kyiv", "Europe", ["Kiev"]),
    ("AE", "United Arab Emirates", "阿拉伯联合酋长国", "Abu Dhabi", "Asia", ["UAE", "Emirates"]),
    ("GB", "United Kingdom", "英国", "London", "Europe", ["UK", "Great Britain", "Britain", "England"]),
    ("TZ", "Tanzania", "坦桑尼亚", "Dodoma", "Africa", ["United Republic of Tanzania"]),
    ("US", "United States", "美国", "Washington, D.C.", "North America", ["USA", "United States of America", "America", "US"]),
    ("UY", "Uruguay", "乌拉圭", "Montevideo", "South America", []),
    ("UZ", "Uzbekistan", "乌兹别克斯坦", "Tashkent", "Asia", []),
    ("VU", "Vanuatu", "瓦努阿图", "Port Vila", "Oceania", []),
    ("VE", "Venezuela", "委内瑞拉", "Caracas", "South America", ["Venezuela (Bolivarian Republic of)"]),
    ("VN", "Vietnam", "越南", "Hanoi", "Asia", ["Viet Nam"]),
    ("YE", "Yemen", "也门", "Sanaa", "Asia", []),
    ("ZM", "Zambia", "赞比亚", "Lusaka", "Africa", []),
    ("ZW", "Zimbabwe", "津巴布韦", "Harare", "Africa", []),
]

countries = [
    {
        "code": code,
        "name": name,
        "zh": zh,
        "capital": capital,
        "continent": continent,
        "flag": flag(code),
        "aliases": aliases,
    }
    for code, name, zh, capital, continent, aliases in rows
]

assert len(countries) == 193, len(countries)
assert len({country["code"] for country in countries}) == 193

with open("data/countries.json", "w", encoding="utf-8") as output:
    json.dump(countries, output, ensure_ascii=False, indent=2)
    output.write("\n")

print("Wrote", len(countries), "countries")
